const Images = {
  appLogo: require('./logo.png'),
  arrowLeft: require('./assets/arrow-left.png'),
  arrowRight: require('./assets/arrow-right.png'),
  image1: require('./assets/image1.png'),
  image2: require('./assets/image2.png'),
  image3: require('./assets/image3.png'),
  image4: require('./assets/image4.png'),
  image5: require('./assets/image5.png'),
  image6: require('./assets/image6.png'),
  loveColor: require('./assets/love-color.png'),
  love: require('./assets/love.png'),
  menu1: require('./assets/menu1.png'),
  menu2: require('./assets/menu2.png'),
  menu3: require('./assets/menu3.png'),
  notif: require('./assets/notif.png'),
  play: require('./assets/play.png'),
  search: require('./assets/search.png'),
  star: require('./assets/star.png'),
  tab1: require('./assets/tab1.png'),
  tab2: require('./assets/tab2.png'),
  tab3: require('./assets/tab3.png'),
  wishlist: require('./assets/wishlist.png'),
}

export default Images
